- name: Install ArchLinux
  hosts: all
  become: True
  vars:
    packages:
      - acpid
      - alsa-firmware
      - alsa-plugins
      - alsa-utils
      - aspell
      - aspell-en
      - aspell-fr
      - bind-tools
      - brasero
      - btrfs-progs
      - chromium
      - cups
      - darktable
      - dialog
      - docker
      - dosfstools
      - dmenu
      - dstat
      - evince
      - exfat-utils
      - feh
      - firefox
      - fuse-exfat
      - gcc-fortran
      - gimp
      - gparted
      - gptfdisk
      - graphviz
      - gsfonts
      - hddtemp
      - htop
      - httpie
      - iotop
      - libcups
      - libreoffice
      - libva-vdpau-driver
      - lm_sensors
      - lsof
      - lxappearance
      - lynx
      - mesa-demos
      - moreutils
      - mpv
      - netctl
      - nethogs
      - ntfs-3g
      - openssh
      - openvpn
      - pkgfile
      - poppler
      - pulseaudio
      - pulseaudio-alsa
      - python-virtualenvwrapper
      - python2-pip
      - rawtherapee
      - rsync
      - smartmontools
      - strace
      - traceroute
      - transmission-gtk
      - ufw
  tasks:
    - name: Install packages on ArchLinux
      pacman: name={{ item }} state=latest
      with_items: packages
      when: ansible_distribution == "ArchLinux"

    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }} mode=0640
      with_items:
        - { src: files/archlinux/dhcpcd.conf, dest: /etc/dhcpcd.conf }
        - { src: files/archlinux/locale.conf, dest: /etc/locale.conf }
        - { src: files/archlinux/locale.gen, dest: /etc/locale.gen }

    - name: Set locale to en_US.UTF-8
      command: localectl set-locale LANG=en_US.UTF-8
