- name: Install Go
  hosts: all
  environment:
    GOPATH: "{{ lookup('env', 'HOME') }}/Go"
  tasks:
    - name: Install bootstrap on ArchLinux
      pacman: name=go state=latest
      when: ansible_distribution == "ArchLinux"

    - name: Set bootstrap on ArchLinux
      set_fact:
        bootstrap: /usr/lib/go
      when: ansible_distribution == "Archlinux"

    - name: Install bootstrap on MacOSX
      homebrew: name=go state=latest
      when: ansible_distribution == "MacOSX"

    - name: Set bootstrap on MacOSX
      set_fact:
        bootstrap: /usr/local/Cellar/go/1.5.1/libexec
      when: ansible_distribution == "MacOSX"

    - name: Clone Go official repository
      git: repo=https://go.googlesource.com/go dest=~/go version=go1.5.1

    - name: Compile Go
      command: ./all.bash creates=~/go/bin/go
      environment:
        GOROOT_BOOTSTRAP: "{{ bootstrap }}"
      args:
        chdir: ~/go/src

    - name: Install Godef
      command: ~/go/bin/go get -u code.google.com/p/rog-go/exp/cmd/godef

    - name: Install Golint
      command: ~/go/bin/go get -u github.com/golang/lint/golint

    - name: Install Gotags
      command: ~/go/bin/go get -u github.com/jstemmer/gotags

    - name: Install Errcheck
      command: ~/go/bin/go get -u github.com/kisielk/errcheck

    - name: Install PostGreSQL drivers
      command: ~/go/bin/go get -u github.com/lib/pq

    - name: Install Oauth
      command: ~/go/bin/go get -u github.com/mrjones/oauth

    - name: Install Gocode
      command: ~/go/bin/go get -u github.com/nsf/gocode

    - name: Install Wego
      command: ~/go/bin/go get -u github.com/schachmat/wego

    - name: Install Hugo
      command: ~/go/bin/go get -u github.com/spf13/hugo

    - name: Install Benchcmp
      command: ~/go/bin/go get -u golang.org/x/tools/cmd/benchcmp

    - name: Install Godoc
      command: ~/go/bin/go get -u golang.org/x/tools/cmd/godoc

    - name: Install Goimports
      command: ~/go/bin/go get -u golang.org/x/tools/cmd/goimports

    - name: Install gorename
      command: ~/go/bin/go get -u golang.org/x/tools/cmd/gorename

    - name: Install vet
      command: ~/go/bin/go get -u golang.org/x/tools/cmd/vet

    - name: Install oracle
      command: ~/go/bin/go get -u golang.org/x/tools/oracle

    - name: Install MongoDB drivers (mgo.v2)
      command: ~/go/bin/go get -u gopkg.in/mgo.v2

    - name: Install Vegeta
      command: "{{ item }}"
      with_items:
        - ~/go/bin/go get -u github.com/tsenart/vegeta
        - ~/go/bin/go install github.com/tsenart/vegeta
