- name: Install I3WM
  hosts: all
  vars:
    packages:
      - adobe-source-code-pro-fonts
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - artwiz-fonts
      - font-bh-ttf
      - font-bitstream-speedo
      - gsfonts
      - i3-wm
      - i3lock
      - i3status
      - mate-themes
      - mate-icon-theme
      - redshift
      - screenfetch
      - scrot
      - sdl_ttf
      - slim
      - terminus-font
      - termite
      - ttf-arphic-uming
      - ttf-baekmuk
      - ttf-bitstream-vera
      - ttf-cheapskate
      - ttf-dejavu
      - ttf-freefont
      - ttf-inconsolata
      - ttf-liberation
      - ttf-ubuntu-font-family
      - xbindkeys
      - xf86-input-evdev
      - xf86-input-synaptics
      - xfce4-terminal
      - xorg-fonts-100dpi
      - xorg-fonts-75dpi
      - xorg-fonts-type1
      - xorg-server-devel
      - xorg-xbacklight
      - xorg-xdpyinfo
      - xorg-xev
      - xorg-xfontsel
      - xorg-xinit
      - xorg-xkill
      - xorg-xmodmap
      - xorg-xprop
      - xorg-xrandr
      - xorg-xrdb
      - xorg-xwininfo
  tasks:
    - name: Install packages on ArchLinux
      become: True
      pacman: name={{ item }} state=latest
      with_items: packages

    - name: Create directories
      file: path={{ item }} state=directory mode=0750
      with_items:
        - ~/.config/fontconfig
        - ~/.config/termite
        - ~/.config/xfce4/terminal
        - ~/.i3
        - ~/.local/share

    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }} mode=0640
      with_items:
        - { src: files/i3/conky_wrapper, dest: ~/.i3/conky_wrapper }
        - { src: files/i3/conkyrc, dest: ~/.i3/conkyrc }
        - { src: files/i3/fonts.conf, dest: ~/.config/fontconfig/fonts.conf }
        - { src: files/i3/gtkrc-2.0, dest: ~/.gtkrc-2.0 }
        - { src: files/i3/i3_config, dest: ~/.i3/config }
        - { src: files/i3/i3lock.png, dest: ~/.i3/i3lock.png }
        - { src: files/i3/termite_config, dest: ~/.config/termite/config }
        - { src: files/i3/xbindkeysrc, dest: ~/.xbindkeysrc }
        - { src: files/i3/xinitrc, dest: ~/.xinitrc }

    - name: Fix permission on conky_wrapper
      file: path=~/.i3/conky_wrapper mode=0540

    - name: Copy fonts
      copy: src=files/i3/fonts dest=~/.local/share

    - name: Update fonts cache
      command: fc-cache -vf ~/.local/share/fonts
