- name: Install Music
  hosts: all
  vars:
    packages:
      - mpc
      - mpd
      - ncmpcpp
  tasks:
    - name: Install XQuartz
      become: True
      homebrew_cask: name=xquartz state=present
      when: ansible_distribution == "MacOSX"

    - name: Install packages on ArchLinux
      become: True
      pacman: name={{ item }} state=latest
      with_items: packages
      when: ansible_distribution == "Archlinux"

    - name: Install packages on MacOSX
      homebrew: name={{ item }} state=latest
      with_items: packages
      when: ansible_distribution == "MacOSX"

    - name: Install beets
      pip: name=beets executable=pip2 extra_args="--upgrade --user"

    - name: Create directories
      file: path={{ item }} state=directory mode=0750
      with_items:
        - ~/.config/beets
        - ~/.ncmpcpp

    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }} mode=0640
      with_items:
        - { src: files/music/beets.yaml, dest: ~/.config/beets/config.yaml }
        - { src: files/music/ncmpcpp.conf, dest: ~/.ncmpcpp/config }
