- name: Install Neovim
  hosts: all
  tasks:
    - name: Install packages on MacOSX
      homebrew: name=neovim state=latest
      when: ansible_distribution == "MacOSX"

    - name: Create directories
      file: path={{ item }} state=directory mode=0750
      with_items:
        - ~/.config/nvim/templates
        - ~/.config/nvim/autoload

    - name: Clone plugins
      git: repo={{ item.src }} dest=~/.config/nvim/bundle/{{ item.dest }} depth=1
      with_items:
        - { dest: airline, src: "https://github.com/bling/vim-airline.git" }
        - { dest: ansible, src: "https://github.com/pearofducks/ansible-vim.git" }
        - { dest: ctrlp, src: "https://github.com/ctrlpvim/ctrlp.vim.git" }
        - { dest: delimitmate, src: "https://github.com/Raimondi/delimitMate.git" }
        - { dest: fugitive, src: "https://github.com/tpope/vim-fugitive.git" }
        - { dest: gitgutter, src: "https://github.com/airblade/vim-gitgutter.git" }
        - { dest: go, src: "https://github.com/fatih/vim-go.git" }
        - { dest: gruvbox, src: "https://github.com/morhetz/gruvbox.git" }
        - { dest: html5, src: "https://github.com/othree/html5.vim.git" }
        - { dest: indentpython, src: "https://github.com/vim-scripts/indentpython.vim.git" }
        - { dest: jedi, src: "https://github.com/davidhalter/jedi-vim.git" }
        - { dest: jinja2, src: "https://github.com/mitsuhiko/jinja2.git" }
        - { dest: neomake, src: "https://github.com/benekastah/neomake" }
        - { dest: surround, src: "https://github.com/tpope/vim-surround.git" }
        - { dest: tcomment_vim, src: "https://github.com/tomtom/tcomment_vim.git" }
        - { dest: virtualenv, src: "https://github.com/jmcantrell/vim-virtualenv.git" }
        - { dest: youcompleteme, src: "https://github.com/Valloric/YouCompleteMe.git" }

    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }} mode=0640
      with_items:
        - { src: files/neovim/init.vim, dest: ~/.config/nvim/init.vim }
        - { src: files/neovim/python.py, dest: ~/.config/nvim/templates/python.py }
        - { src: files/neovim/pathogen.vim, dest: ~/.config/nvim/autoload/pathogen.vim }

    - name: Be able to switch back to VIM
      file: path={{ item.dest }} src={{ item.src }} state=link
      with_items:
        - { dest: ~/.vim, src: ~/.config/nvim }
        - { dest: ~/.vimrc, src: ~/.config/nvim/init.vim }


    - name: Compile YouCompleteMe
      command: python2 ~/.config/nvim/bundle/youcompleteme/install.py --gocode-completer
