directory: ~/Music
import:
        move:   yes
threaded:       yes
color:          yes
paths:
        default: Albums/$albumartist/$album/$track $title
        singleton: Singletons/$artist $title
        comp: Compilations/$album/$track $title
        albumtype:soundtrack: Soundtracks/$album/$track $title
