pkg.installed:
  - pkgs:
    - chromium-browser
    - default-jre
    - gimp
    - gitg
    - gitk
    - gource
    - indicator-multiload
    - inkscape
    - meld
    - scrot
    - ubuntu-restricted-extras
    - unetbootin
    - vlc
