# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="lukerandall"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(archlinux brew docker encode64 git gpg-agent pass pip python sublime sudo systemd virtualenvwrapper)

source $ZSH/oh-my-zsh.sh

# Fix GOPATH variable
export GOPATH=~/Go

# Set default editor
export EDITOR=vim

# Customize to your needs...
PATH=/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
PATH=~/.local/bin:$PATH
PATH=$PATH:~/go/bin:~/.dotfiles/scripts:$GOPATH/bin
PATH=/usr/lib/ccache:$PATH
PATH=$PATH:~/Library/Python/2.7/bin

source ~/.base16/base16-default.dark.sh

alias maj="sudo apt-get update && sudo apt-get dist-upgrade"

alias ta="tmux attach"

# Only load .Xmodmap if X server is running.
# [ -n "${XAUTHORITY+x}" ] && xmodmap ~/.Xmodmap

# Fix Solarized theme in tmux session
alias tmux="TERM=screen-256color-bce tmux"

# Ignore HTTPS certificate by default with wget
alias wget="wget --no-check-certificate"

# Activate virtualenvwrapper
#export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
#if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
#	source /usr/local/bin/virtualenvwrapper.sh
#else
#	source /etc/bash_completion.d/virtualenvwrapper
#fi

# Task aliases
alias tl="task list"

# Launch a small webserver
alias ws="python -m SimpleHTTPServer"

# Pip variables
export PIP_DOWNLOAD_CACHE=~/.pip/cache

# NPR Radio
alias npr="mplayer http://nprdmp.ic.llnwd.net/stream/nprdmp_live01_mp3"

# Flush memcached objects
alias flush_memcached="echo flush_all | nc 127.0.0.1 11211"

alias go_light="xrdb -merge ~/.Xresources-light"
alias go_dark="xrdb -merge ~/.Xresources"

# We want VIM all the time
alias vi="vim"

# Display exif information and fullscreen by default
alias feh="feh -F --draw-exif"

# Display the whole year with monday as first day and week numbers
alias cal="cal -m -3 -y -w"

# Change the current wallpaper by picking up a random one
alias chwall="[[ -d ~/Sync/Wallpapers ]] && feh --randomize --bg-fill ~/Sync/Wallpapers/*"

# Only play audio on video files
alias listen_video="mplayer -novideo"

# Pretty JSON
alias pretty_json="python -m json.tool"

# ... with colors
alias pretty_json_colorized="pretty_json | pygmentize -l javascript"

# Download subtitles for all mkv files of current directory
alias sub_en="ls -1 *.mkv | xargs -n 1 subdl --lang=eng; subliminal *.mkv -l en"
alias sub_fr="ls -1 *.mkv | xargs -n 1 subdl --lang=fre; subliminal *.mkv -l fr"

# Watch disk flushing
alias watch_flush="watch grep -e Dirty: -e Writeback: /proc/meminfo"
