#!/bin/sh
#

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Fix low backlight issue
xbacklight = 100

# Bind multimedia keys
xbindkeys

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

exec i3
