# Path to your oh-my-zsh configuration.
# Oh my ZSH !
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="lukerandall"
DISABLE_AUTO_UPDATE="true"
plugins=(git pass vi-mode virtualenvwrapper)
source $ZSH/oh-my-zsh.sh

# Launch ssh-agent
if ! pgrep -u $USER ssh-agent > /dev/null; then
	ssh-agent > ~/.ssh/agent
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
	eval $(<~/.ssh/agent)
fi
ssh-add -l > /dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'

# Fix GOPATH variable
export GOPATH=~/Go

# Set default editor
export EDITOR=nvim

# Customize to your needs...
PATH=/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
PATH=~/.local/bin:$PATH
PATH=$PATH:~/.dotfiles/scripts:$GOPATH/bin
PATH=/usr/lib/ccache:$PATH
PATH=$PATH:~/Library/Python/2.7/bin

# Set TERM variable
export TERM=xterm

# Ignore HTTPS certificate by default with wget
alias wget="wget --no-check-certificate"

# Launch a small webserver
alias ws="python -m SimpleHTTPServer"

# Pip variables
export PIP_DOWNLOAD_CACHE=~/.pip/cache

# NPR Radio
alias npr="mplayer http://nprdmp.ic.llnwd.net/stream/nprdmp_live01_mp3"

# Flush memcached objects
alias flush_memcached="echo flush_all | nc 127.0.0.1 11211"

# We want Neovim all the time
alias vi="nvim"
alias vim="nvim"

# Display exif information and fullscreen by default
alias feh="feh -F --draw-exif"

# Display the whole year with monday as first day and week numbers
alias cal="cal -m -3 -y -w"

# Change the current wallpaper by picking up a random one
alias chwall="[[ -d ~/Sync/Wallpapers ]] && feh --randomize --bg-fill ~/Sync/Wallpapers/*"

# Only play audio on video files
alias listen_video="mplayer -novideo"

# Pretty JSON
alias pretty_json="python -m json.tool"

# ... with colors
alias pretty_json_colorized="pretty_json | pygmentize -l javascript"

# Watch disk flushing
alias watch_flush="watch grep -e Dirty: -e Writeback: /proc/meminfo"

# Beet import current directory
alias bi.="beet import ."
