directory: ~/Music
library: ~/.config/beets/library.db
threaded: yes
ui:
  color: yes
import:
  default_action: skip
  languages: en
  move: yes
replace:
  '[?.":\!`]': ''
  '[*<>\/\\]': '-'
  '✝': '+'
  '&': 'and'
original_date: no
plugins: the convert embedart fetchart ftintitle lastgenre missing scrub duplicates
#asciify_paths: yes
paths:
  default: Albums/%the{$albumartist}/$album%aunique{}/$track $title
  singleton: Singletons/%the{$artist}/$title
  comp: Compilations/$album%aunique{}/$track $title
  albumtype:soundtrack: Soundtracks/$album/$track $title
match:
  preferred:
    countries: ['FR', 'US', 'GB|UK']
embedart:
  remove_art_file: yes
convert:
  format: aac-128
  dest: /data/convert/aac-128
  formats:
          aac-128:
                  command: ffmpeg -i $source -y -vn -acodec aac -ab 128k -vn $dest
                  extension: m4a
          aac-160:
                  command: ffmpeg -i $source -y -vn -acodec aac -ab 160k -vn $dest
                  extension: m4a
          aac-192:
                  command: ffmpeg -i $source -y -vn -acodec aac -ab 192k -vn $dest
                  extension: m4a
          aac-vbr-1:
                  command: ffmpeg -i $source -y -vn -acodec aac -vn -vbr 1 $dest
                  extension: m4a
          aac-vbr-2:
                  command: ffmpeg -i $source -y -vn -acodec aac -vn -vbr 2 $dest
                  extension: m4a
          aac-vbr-3:
                  command: ffmpeg -i $source -y -vn -acodec aac -vn -vbr 3 $dest
                  extension: m4a
          aac-vbr-4:
                  command: ffmpeg -i $source -y -vn -acodec aac -vn -vbr 4 $dest
                  extension: m4a
          aac-vbr-5:
                  command: ffmpeg -i $source -y -vn -acodec aac -vn -vbr 5 $dest
                  extension: m4a
