#! /bin/sh

sxhkd &
polybar dark &

# bspc monitor -d 一 ニ 三 四 五 六 七 八 九 十
bspc monitor -d 1 2 3 4 5

bspc config border_width          4
bspc config window_gap            12

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

