- name: Install I3WM
  hosts: all
  vars:
    packages:
      - adobe-source-code-pro-fonts
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - artwiz-fonts
      - font-bh-ttf
      - font-bitstream-speedo
      - gsfonts
      - mate-themes
      - mate-icon-theme
      - sdl_ttf
      - terminus-font
      - ttf-arphic-uming
      - ttf-baekmuk
      - ttf-bitstream-vera
      - ttf-cheapskate
      - ttf-dejavu
      - ttf-freefont
      - ttf-inconsolata
      - ttf-liberation
      - ttf-ubuntu-font-family
      - xf86-input-evdev
      - xf86-input-synaptics
      - xorg-fonts-100dpi
      - xorg-fonts-75dpi
      - xorg-fonts-type1
      - xorg-xbacklight
      - xorg-xdpyinfo
      - xorg-xev
      - xorg-xfontsel
      - xorg-xkill
      - xorg-xmodmap
      - xorg-xprop
      - xorg-xrandr
      - xorg-xrdb
      - xorg-xwininfo
  tasks:
    - name: Install packages on ArchLinux
      become: True
      pacman: name={{ item }} state=latest
      with_items: packages
