- name: Install I3WM
  hosts: all
  vars:
    packages:
      - adobe-source-code-pro-fonts
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - artwiz-fonts
      - font-bh-ttf
      - font-bitstream-speedo
      - gsfonts
      - i3-wm
      - i3lock
      - i3status
      - mate-themes
      - mate-icon-theme
      - redshift
      - screenfetch
      - scrot
      - sdl_ttf
      - slim
      - terminus-font
      - termite
      - ttf-arphic-uming
      - ttf-baekmuk
      - ttf-bitstream-vera
      - ttf-cheapskate
      - ttf-dejavu
      - ttf-freefont
      - ttf-inconsolata
      - ttf-liberation
      - ttf-ubuntu-font-family
      - xbindkeys
      - xf86-input-evdev
      - xf86-input-synaptics
      - xfce4-terminal
      - xorg-fonts-100dpi
      - xorg-fonts-75dpi
      - xorg-fonts-type1
      - xorg-server-devel
      - xorg-xbacklight
      - xorg-xdpyinfo
      - xorg-xev
      - xorg-xfontsel
      - xorg-xinit
      - xorg-xkill
      - xorg-xmodmap
      - xorg-xprop
      - xorg-xrandr
      - xorg-xrdb
      - xorg-xwininfo
  tasks:
    - name: Install packages on ArchLinux
      become: True
      pacman: name={{ item }} state=latest
      with_items: packages

    - name: Fix permission on conky_wrapper
      file: path=~/.i3/conky_wrapper mode=0540

    - name: Update fonts cache
      command: fc-cache -vf ~/.local/share/fonts
