- name: Install Mail
  hosts: all
  vars:
    packages:
      - abook
      - isync
      - pass
      - mutt
      - msmtp
      - notmuch
  tasks:
    - name: Install packages on ArchLinux
      become: True
      pacman: name={{ item }} state=latest
      with_items: packages
      when: ansible_distribution == "Archlinux"
