set mat=2 " How many tenths of a second to blink when matching brackets
set nobackup
set noswapfile

set smartindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Syntastic
set rtp+=~/.vim/syntastic
let g:syntastic_check_on_open=0
let g:syntastic_python_checkers=['flake8']
let g:syntastic_python_flake8_post_args='--ignore=E501'

set omnifunc=syntaxcomplete#Complete

" Navigate buffers
noremap <F1> :bprev<CR>
noremap <F2> :bnext<CR>

" Proper indentation for Python
autocmd FileType python set tabstop=4
autocmd FileType python set softtabstop=4
autocmd FileType python set shiftwidth=4

" Autocompletion
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType go set omnifunc=go#complete#Complete
